@backend_HostAddress = http://localhost:5156
POST  {{backend_HostAddress}}/register
Content-Type: application/json

 {
   "username":"Roman Dew",
   "email": "roman@gmail.com",
   "password": "s@etwyxwuw"
  }
###

POST   {{backend_HostAddress}}/login
Content-Type: application/json

 {
   "email": "roman@gmail.com",
   "password": "s@etwyxwuw"
  }

###
POST  {{backend_HostAddress}}/addproduct
Content-Type: application/json

 {
   "name":"Sapotta",
    "description":"Corfoc",
    "image":"image 2"
  }
###

POST   {{backend_HostAddress}}/viewproduct
Content-Type: application/json

 {
   "name": "Sapotta"
  }
